package com.givan.tic_tac_toe;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

public class md extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_md);
        Button b=(Button)findViewById(R.id.button13);
        b.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(getApplicationContext(), Madness.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(intent);
                finish();
            }
        });

    }
    /*public void ct(){

        long time= System.currentTimeMillis();
        if(time%9==0)
        {
            if(a[1]==1)
            {
                b1.setClickable(false);
                a[1]=-1;
                showc();
                b1.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==1)
        {
            if(a[1]==1)
            {
                b1.setClickable(false);
                a[1]=-1;
                showc();
                b1.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==2)
        {
            if(a[2]==2)
            {
                b2.setClickable(false);
                a[2]=-1;
                showc();
                b2.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==3)
        {
            if(a[3]==3)
            {
                b3.setClickable(false);
                a[3]=-1;
                showc();
                b3.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==4)
        {
            if(a[4]==4)
            {
                b4.setClickable(false);
                a[4]=-1;
                showc();
                b4.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==5)
        {
            if(a[5]==5)
            {
                b5.setClickable(false);
                a[5]=-1;
                showc();
                b5.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==6)
        {
            if(a[6]==6)
            {
                b6.setClickable(false);
                a[6]=-1;
                showc();
                b6.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==7)
        {
            if(a[7]==7)
            {
                b7.setClickable(false);
                a[7]=-1;
                showc();
                b7.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==8)
        {
            if(a[8]==8)
            {
                b8.setClickable(false);
                a[8]=-1;
                showc();
                b8.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==0)
        {
            if(a[1]==1)
            {
                b1.setClickable(false);
                a[1]=-1;
                showc();
                b1.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==1)
        {
            if(a[1]==1)
            {
                b1.setClickable(false);
                a[1]=-1;
                showc();
                b1.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==2)
        {
            if(a[2]==2)
            {
                b2.setClickable(false);
                a[2]=-1;
                showc();
                b2.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==3)
        {
            if(a[3]==3)
            {
                b3.setClickable(false);
                a[3]=-1;
                showc();
                b3.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==4)
        {
            if(a[4]==4)
            {
                b4.setClickable(false);
                a[4]=-1;
                showc();
                b4.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==5)
        {
            if(a[5]==5)
            {
                b5.setClickable(false);
                a[5]=-1;
                showc();
                b5.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==6)
        {
            if(a[6]==6)
            {
                b6.setClickable(false);
                a[6]=-1;
                showc();
                b6.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }if(time%9==7)
        {
            if(a[7]==7)
            {
                b7.setClickable(false);
                a[7]=-1;
                showc();
                b7.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }
        if(time%9==8)
        {
            if(a[8]==8)
            {
                b8.setClickable(false);
                a[8]=-1;
                showc();
                b8.setText("X");
                return;
            }
            else
            {
                time++;
            }
        }



    }*/
}
